import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Advertisement from "@/components/Advertisement";
import Footer from "@/components/layouts/Footer";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Estate Business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Advertisement />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
